# Generated by Django 4.1.7 on 2023-04-19 14:21

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Pfd',
            field=models.FileField(upload_to='media/Course', validators=[apps.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='keystone',
            name='Image',
            field=models.ImageField(default='project.jpg', upload_to='media/Project'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Svg_Image',
            field=models.FileField(upload_to='media/Lang', validators=[apps.models.validate_svg]),
        ),
        migrations.AlterField(
            model_name='program_language',
            name='Svg_Image',
            field=models.FileField(upload_to='media/ProLang', validators=[apps.models.validate_svg]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Image',
            field=models.ImageField(default='skill.jpg', upload_to='media/Skill'),
        ),
    ]
