# Generated by Django 4.1.7 on 2023-04-20 15:46

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_courses_pfd_alter_keystone_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='program_language',
            name='Svg_Image',
            field=models.FileField(upload_to='media/plang', validators=[apps.models.validate_svg]),
        ),
    ]
