# Generated by Django 4.1.7 on 2023-04-25 01:33

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_article_title_alter_program_language_svg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carosel',
            name='Image',
            field=models.ImageField(upload_to='carosel'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Certificate',
            field=models.ImageField(upload_to='Course'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Pfd',
            field=models.FileField(upload_to='Course', validators=[apps.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='education',
            name='img',
            field=models.ImageField(upload_to='education'),
        ),
        migrations.AlterField(
            model_name='intrest',
            name='Svg_Image',
            field=models.FileField(upload_to='Skill', validators=[apps.models.validate_svg]),
        ),
        migrations.AlterField(
            model_name='keystone',
            name='Image',
            field=models.ImageField(default='project.jpg', upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Svg_Image',
            field=models.FileField(upload_to='Lang', validators=[apps.models.validate_svg]),
        ),
        migrations.AlterField(
            model_name='program_language',
            name='Svg_Image',
            field=models.FileField(upload_to='plang', validators=[apps.models.validate_svg]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Image',
            field=models.ImageField(default='skill.jpg', upload_to='Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Svg_Image',
            field=models.FileField(upload_to='Skill', validators=[apps.models.validate_svg]),
        ),
        migrations.AlterField(
            model_name='worked',
            name='img',
            field=models.ImageField(upload_to='work'),
        ),
    ]
