# Generated by Django 4.1.7 on 2023-04-25 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_carosel_image_alter_courses_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keystone',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Skill'),
        ),
    ]
